### ISSUE TITLE
Path sorunları

### ISSUE THREAD

**Issue by berkbulgan** [basibosmuhendis/hair-saloon-homework#1]
https://github.com/HuseyinCahitCodes/hair-saloon-homework/blob/2af0dfbc46b859528035aafaba3390b1ca4a96ad/template/index.html#L29

URL'de görebileceğin yerde ve bir kaç yerde daha fotoğraf path'lerinde sorun var.

**Comment by HuseyinCahitCodes** [comment]
Uyarıların için teşekkür ederim. Path sorunları düzeltildi.
